version: 2.1
orbs:
  node: circleci/node@5.0.0

defaults: &defaults
  executor:
    name: node/default
    tag: 'lts'
  working_directory: ~/app

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ~/app
      - run:
          name: build nuxt app site
          command: yarn run build
      - persist_to_workspace:
          root: ~/app
          paths: [.]
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Lint code.
          command: yarn run lint
      - run:
          command: yarn run test:unit
          name: Run unit tests
      - store_test_results:
          path: test-results

  build-storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          command: yarn workspace @dpc-sdp/ripple-ui-core storybook:build
          name: Build static storybook
      - persist_to_workspace:
          root: ~/app
          paths:
            - packages/ripple-ui-core/storybook-static

  test-storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          command: yarn workspace @dpc-sdp/ripple-ui-core test:storybook-ci
          name: Run storybook Tests

  chromatic:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
        # Runs the Chromatic CLI
      - run: yarn chromatic --storybook-build-dir=/packages/ripple-ui-core/storybook-static --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes

workflows:
  commit:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-storybook:
          requires:
            - build
            - build-storybook
      - chromatic:
          requires:
            - build
            - build-storybook
