version: 2.1
orbs:
  node: circleci/node@5.0.0

defaults: &defaults
  docker:
    - image: cypress/base:16.13.0
      environment:
        TERM: xterm
        TZ: 'Australia/Melbourne'
        NUXT_PUBLIC_API_URL: http://localhost:3001
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD
  working_directory: ~/app

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          key: v10-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
      - persist_to_workspace:
          root: ~/app
          paths: [.]
  unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Lint code.
          command: yarn run lint
      - run:
          command: yarn run test:unit
          name: Run unit tests
      - store_test_results:
          path: test-results

  build-docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: build docs site
          command: yarn run build:docs

  build-examples:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: build example apps
          command: yarn run build:examples
      - persist_to_workspace:
          root: ~/app
          paths: [.]

  integration-nuxt:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - v10-deps-{{ checksum "yarn.lock" }}
            - v10-deps-{{ .Branch }}
            - v9-deps
      - run:
          command: yarn run ci:nuxt-app
          name: Run integration tests with Cypress
      - store_artifacts:
          path: examples/nuxt-app/test/videos
      - store_artifacts:
          path: examples/nuxt-app/test/screenshots
      - store_test_results:
          path: examples/nuxt-app/test/results

  build-storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          command: yarn build:storybook
          name: Build static storybook
      - persist_to_workspace:
          root: ~/app
          paths:
            - storybook-static

  test-storybook:
    docker:
      - image: mcr.microsoft.com/playwright:v1.25.0-focal
    environment:
      NODE_ENV: development
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          command: yarn test:storybook-ci
          name: Run storybook Tests

  chromatic:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
        # Runs the Chromatic CLI for core and forms packages
      - run: yarn chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes --exit-once-uploaded

workflows:
  commit:
    jobs:
      - build
      - unit:
          requires:
            - build
      - build-storybook:
          requires:
            - build
      - build-examples:
          requires:
            - build
      - integration-nuxt:
          requires:
            - build-examples
      - test-storybook:
          requires:
            - build-storybook
      - chromatic:
          requires:
            - build-storybook
