version: 2.1
orbs:
  node: circleci/node@5.0.0

defaults: &defaults
  executor:
    name: node/default
    tag: 'lts'
  working_directory: ~/app

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ~/app
          cache-version: v1
          with-cache: true
      - persist_to_workspace:
          root: ~/app
          paths: [.]
  unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Lint code.
          command: yarn run lint
      - run:
          command: yarn run test:unit
          name: Run unit tests
      - store_test_results:
          path: test-results

  build-docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: build docs site
          command: yarn run build:docs

  build-examples:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: build example apps
          command: yarn run build:examples
      - persist_to_workspace:
          root: ~/app
          paths: [.]

  integration-nuxt:
    working_directory: ~/app
    docker:
      - image: cypress/base:14.16.0
        environment:
          TERM: xterm

    steps:
      - attach_workspace:
          at: ~/app
      - run:
          command: yarn run ci:nuxt-app
          name: Run integration tests with Cypress
      - store_artifacts:
          path: examples/nuxt-app/test/videos
      - store_artifacts:
          path: examples/nuxt-app/test/screenshots
      - store_test_results:
          path: examples/nuxt-app/test/results

  build-storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          command: yarn build:storybook
          name: Build static storybook
      - persist_to_workspace:
          root: ~/app
          paths:
            - storybook-static

  test-storybook:
    docker:
      - image: mcr.microsoft.com/playwright:v1.25.0-focal
    environment:
      NODE_ENV: development
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          command: yarn test:storybook-ci
          name: Run storybook Tests

  chromatic:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
        # Runs the Chromatic CLI for core and forms packages
      - run: yarn chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes --exit-once-uploaded

workflows:
  commit:
    jobs:
      - build
      - unit:
          requires:
            - build
      - build-storybook:
          requires:
            - build
      - build-examples:
          requires:
            - build
      - integration-nuxt:
          requires:
            - build-examples
      - test-storybook:
          requires:
            - build-storybook
      - chromatic:
          requires:
            - build-storybook
