[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main', 'develop', 'feature/docs-site']
  template = "hierarchical"
